language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.11"
matrix:
  allow_failures:
    - node_js: "0.11"
  fast_finish: true
sudo: false
before_install:
  - "test $TRAVIS_NODE_VERSION != '0.6' || sed -i 's/devDependencies/optionalDependencies/' package.json"
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm install -g npm@1.2.8000"
script:
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm test"
  - "test $TRAVIS_NODE_VERSION  = '0.6' || npm run-script test-travis"
after_script:
  - "test $TRAVIS_NODE_VERSION = '0.10' && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
