language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
before_install: "test $TRAVIS_NODE_VERSION = '0.8' && npm install -g npm@1.2.8000 || true"
script: "npm run-script test-travis"
after_script: "test $TRAVIS_NODE_VERSION = '0.10' && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
