language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
sudo: false
before_install:
  # Remove all non-test dependencies
  - npm rm --save-dev bluebird
  - npm rm --save-dev co
  - npm rm --save-dev cogent
  - npm rm --save-dev csv-parse
  - npm rm --save-dev gnode
  - npm rm --save-dev raw-body
  - npm rm --save-dev stream-to-array

  # Setup Node.js version-specific dependencies
  - test $TRAVIS_NODE_VERSION != '0.6' || npm rm --save-dev istanbul
  - test $TRAVIS_NODE_VERSION != '0.8' || npm install -g npm@1.2.8000
script:
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm test"
  - "test $TRAVIS_NODE_VERSION  = '0.6' || npm run-script test-travis"
after_script:
  - "test $TRAVIS_NODE_VERSION != '0.6' && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
